### ISSUE TITLE
Use Jumploader when exporting Fabric modpacks for Twitch

### ISSUE THREAD

**Issue by redstonekasi** [comp500/packwiz#5]
# Description of bug
When exporting a pack using `packwiz cf export` and trying to import the `export.zip` in Twitch it gives the error shown below.

# Reproduction steps
1. Create new pack with `packwiz init`
2. Select `fabric` as modloader and use latest version.
3. Add any mod (haven't tried it without mods)
4. Run `packwiz cf export` and import the zip in Twitch.

# Images
![image](https://user-images.githubusercontent.com/42352565/94341095-11e62a80-0007-11eb-944f-f6f272c9cfdd.png)

# Assumption
I don't know anything about the format that Twitch uses for exporting modpacks but I guess it maybe because in the `export.zip/manifest.json` file the `minecraft.modLoaders` property is an empty array.

**Comment by comp500** [comment]
As stated on Discord: Twitch doesn't support launching Fabric, so packwiz will make an empty array for the modloader list. I can make packwiz add Jumploader and select Forge (configurable) when exporting to the CurseForge format, so that Fabric packs can be exported easily.

For now, you can select Forge and add Jumploader manually.
