### ISSUE TITLE
Mod/Client-related Configuration Files (and *packs)

### ISSUE THREAD

**Issue by schmannie** [comp500/packwiz#59]
Hey there!

Thanks for your great work! I'm not sure if I missed some part of the documentation or if my assumptions are flawed, but... how do I configure the installed mods for the modpack? Can I change client settings (`options.txt`)? Right now, I make these changes in a MultiMC instance (that I call "Staging") as well as setup the pre-run command to use the packwiz installer.

Is there a way to update configuration files through the packwiz method? What about resourcepacks, shaderpacks, etc.?

Thanks!

EDIT: My gut feeling told me that I should be able to just drop the `.minecraft/config` folder in my packwiz modpack, and refresh indices to sync those to my clients as well -- I missed the documentation for that, so I simply haven't tried that yet. Would that work?

**Comment by comp500** [comment]
Yep, just put the config files in a config folder in your pack, and they'll be downloaded into `.minecraft/config` by packwiz-installer. The same works for `options.txt` and resource packs - the location of `pack.toml` is where files are copied from into `.minecraft`.

Note that for `options.txt` you'll likely want to add `preserve = true` to the index entry, so that the file isn't overwritten if it already exists (so user changes aren't lost)

For resource packs/shader packs on CurseForge, you can use a `.toml` metadata file to download them directly from CurseForge, though it's a bit tricky to set up (you probably need to manually pass the addon and file IDs, and mark the file as `metafile = true` in the index)

**Comment by schmannie** [comment]
Oh okay! Should've just gone with my gut-feeling then. Thank you!
